repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -  id: double-quote-string-fixer
    -  id: pretty-format-json
       args: [--autofix, --no-sort-keys]
    -  id: requirements-txt-fixer
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.7.0
    hooks:
    -   id: seed-isort-config
        args: [--application-directories, "src:."]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.16
    hooks:
    - id: isort
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        description: wemake-python-styleguide enforcement
        entry: flake8
        args: ["--config=setup.cfg"]
        language: python
        types: [python]
default_language_version:
  python: python3.8
