version: "3"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
  web:
    build: .
    volumes:
      - .:/var/www/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
