version: "3"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
  web:
    build: .
    volumes:
      - .:/var/www/app
    ports:
      - "5000:5000"
    command:
      bash -c "alembic upgrade head && python main.py"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - API_HOST=web
      - PRODUCT_API_BASE_URL=http://challenge-api.luizalabs.com
    env_file:
      - .env
