"""add table wished_product

Revision ID: 7c9a579c7ae1
Revises: d36792eeb113
Create Date: 2020-09-07 00:42:42.007450

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '7c9a579c7ae1'
down_revision = 'd36792eeb113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'wished_product',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('customer_id', sa.Integer(), nullable=True),
        sa.Column('product_id', sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customer.id'],),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wished_product')
    # ### end Alembic commands ###
